version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - my_network

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongodb_data:/data/db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mongodb_data:
